## Arrays

### 1.Array

In [2]:
import array

In [3]:
# creation

arr1 = array.array('i', [10, 20, 30, 40, 50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [4]:
# access

arr1[2]

30

In [5]:
arr1[3]

40

In [6]:
#traverse

for element in arr1:
    print(element, end =" ")

10 20 30 40 50 

In [7]:
# insertion 

arr1.insert(3, 35);

In [8]:
print(arr1)

array('i', [10, 20, 30, 35, 40, 50])


In [9]:
# Deletion

arr1.remove(30) #remove first occerance of 30
print(arr1)

array('i', [10, 20, 35, 40, 50])


In [10]:
#Updation

arr1[2] = 30

print(arr1)

array('i', [10, 20, 30, 40, 50])


In [11]:
#Sorting

arr2 = array.array('i', [60, 70, 80])

arr3 = array.array('i', [4, 7, 3, 9, 2, 6])

print(f'arr2 is {arr2}')

print(f'arr3 is {arr3}')

arr2 is array('i', [60, 70, 80])
arr3 is array('i', [4, 7, 3, 9, 2, 6])


In [12]:
sorted(arr3)

[2, 3, 4, 6, 7, 9]

In [13]:
#convert this sorted list to sorted array
sorted_arr3 = array.array('i', sorted(arr3))
print(sorted_arr3)

array('i', [2, 3, 4, 6, 7, 9])


In [14]:
#Merge

print(f'arr1 is {arr1}')

print(f'arr2 is {arr2}')

print(f'mering arr1 and arr2, we get {arr1 + arr2}')

arr1 is array('i', [10, 20, 30, 40, 50])
arr2 is array('i', [60, 70, 80])
mering arr1 and arr2, we get array('i', [10, 20, 30, 40, 50, 60, 70, 80])


In [17]:
arr4 = arr1 + arr2

arr4

array('i', [10, 20, 30, 40, 50, 60, 70, 80])

In [18]:
# Splitting

ix = int(len(arr4) / 2 )
ix

4

In [19]:
# splitting on ix index
arr4[:ix]

array('i', [10, 20, 30, 40])

In [20]:
arr4[ix:]

array('i', [50, 60, 70, 80])

#### 2. Numpy

In [1]:
import numpy as np

In [4]:
# creation

np1 = np.array([10, 20, 30, 40, 50])
np2 = np.array([50, 60, 70])

print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70]


In [5]:
np1

array([10, 20, 30, 40, 50])

In [8]:
# access

np1[2]

30

In [9]:
#traverse

for ele in np1:
    print(ele, end = " ")

10 20 30 40 50 

In [10]:
# insertion

np.insert(np1, 3, 35)

array([10, 20, 30, 35, 40, 50])

In [11]:
# deletion

np.delete(np1, 3)

array([10, 20, 30, 50])

In [ ]:
#updation

np1[2] = 35
print(np1)

[10 20 35 40 50]


In [14]:
# sorting

np3 = np.array([5, 3, 4, 2,6 , 9])

np3

array([5, 3, 4, 2, 6, 9])

In [15]:
np.sort(np3)

array([2, 3, 4, 5, 6, 9])

In [17]:
# merging

np3 = np.concatenate((np1, np2))

np3

array([10, 20, 35, 40, 50, 50, 60, 70])

In [19]:
# splitting

split1, split2 = np.array_split(np3, 2)  ## 2 stands two parts

In [20]:
split1

array([10, 20, 35, 40])

In [21]:
split2

array([50, 50, 60, 70])